2025-06-12 18:09:23,772 - INFO - Programa interrumpido por el usuario
2025-06-13 23:58:23,238 - INFO - Programa interrumpido por el usuario
2025-06-14 17:34:37,190 - INFO - Programa interrumpido por el usuario
2025-06-14 17:36:17,095 - INFO - Programa interrumpido por el usuario
2025-06-14 17:47:35,840 - INFO - Programa interrumpido por el usuario
2025-06-14 18:13:07,031 - INFO - Programa interrumpido por el usuario
2025-06-14 18:18:51,303 - INFO - Programa interrumpido por el usuario
2025-06-14 18:24:05,787 - INFO - Programa interrumpido por el usuario
2025-06-14 18:26:09,819 - INFO - Programa interrumpido por el usuario
2025-06-14 18:31:19,600 - INFO - Programa interrumpido por el usuario
2025-06-14 18:32:11,569 - INFO - Programa interrumpido por el usuario
2025-06-14 18:32:53,042 - INFO - Programa interrumpido por el usuario
2025-06-14 18:33:51,750 - INFO - Programa interrumpido por el usuario
2025-06-14 18:47:42,888 - INFO - Programa interrumpido por el usuario
2025-06-14 18:49:56,454 - INFO - Programa interrumpido por el usuario
2025-06-14 18:59:29,900 - INFO - Programa interrumpido por el usuario
2025-06-14 19:01:20,423 - INFO - Programa interrumpido por el usuario
2025-06-15 18:17:23,473 - INFO - Programa interrumpido por el usuario
2025-06-15 18:22:27,153 - INFO - Programa interrumpido por el usuario
2025-06-15 18:28:54,635 - INFO - Programa interrumpido por el usuario
2025-06-15 18:40:06,429 - INFO - Programa interrumpido por el usuario
2025-06-15 18:40:55,037 - INFO - Programa interrumpido por el usuario
2025-06-15 18:42:26,627 - INFO - Programa interrumpido por el usuario
2025-06-15 18:43:29,577 - INFO - Programa interrumpido por el usuario
2025-06-15 18:47:15,679 - INFO - Programa interrumpido por el usuario
2025-06-15 18:48:31,680 - INFO - Programa interrumpido por el usuario
2025-06-15 18:50:24,531 - INFO - Programa interrumpido por el usuario
2025-06-15 18:53:39,393 - INFO - Programa interrumpido por el usuario
2025-06-15 18:59:02,752 - INFO - Programa interrumpido por el usuario
2025-06-15 19:06:57,884 - INFO - Programa interrumpido por el usuario
2025-06-15 19:08:51,839 - INFO - Programa interrumpido por el usuario
2025-06-15 19:09:57,737 - INFO - Programa interrumpido por el usuario
2025-06-15 19:14:18,136 - INFO - Programa interrumpido por el usuario
2025-06-15 19:15:24,266 - INFO - Programa interrumpido por el usuario
2025-06-15 19:16:03,139 - INFO - Programa interrumpido por el usuario
2025-06-15 19:18:37,538 - INFO - Programa interrumpido por el usuario
2025-06-15 19:35:07,953 - INFO - Programa interrumpido por el usuario
2025-06-15 19:36:06,176 - ERROR - Error en la inicialización del sistema: CinemaServices.agregar_pelicula() takes 5 positional arguments but 6 were given
Traceback (most recent call last):
  File "c:\Users\Ale\Desktop\Infórmatica\Repos\cine-CG\main.py", line 57, in main
    app.ejecutar()
  File "c:\Users\Ale\Desktop\Infórmatica\Repos\cine-CG\interfaz_usuario.py", line 540, in ejecutar
    self.gestionar_peliculas()
  File "c:\Users\Ale\Desktop\Infórmatica\Repos\cine-CG\interfaz_usuario.py", line 65, in gestionar_peliculas
    self.agregar_pelicula()
  File "c:\Users\Ale\Desktop\Infórmatica\Repos\cine-CG\interfaz_usuario.py", line 98, in agregar_pelicula
    resultado = self.cinema_services.agregar_pelicula(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: CinemaServices.agregar_pelicula() takes 5 positional arguments but 6 were given
2025-06-15 19:40:19,802 - INFO - Programa interrumpido por el usuario
2025-06-15 19:43:21,044 - ERROR - Error en la inicialización del sistema: no such table: Genero
Traceback (most recent call last):
  File "c:\Users\Ale\Desktop\Infórmatica\Repos\cine-CG\main.py", line 57, in main
    app.ejecutar()
  File "c:\Users\Ale\Desktop\Infórmatica\Repos\cine-CG\interfaz_usuario.py", line 540, in ejecutar
    self.gestionar_peliculas()
  File "c:\Users\Ale\Desktop\Infórmatica\Repos\cine-CG\interfaz_usuario.py", line 65, in gestionar_peliculas
    self.agregar_pelicula()
  File "c:\Users\Ale\Desktop\Infórmatica\Repos\cine-CG\interfaz_usuario.py", line 82, in agregar_pelicula
    generos = self.cinema_services.obtener_generos()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Ale\Desktop\Infórmatica\Repos\cine-CG\servicios_del_cine.py", line 207, in obtener_generos
    cursor.execute("SELECT idGenero, nombreGenero FROM Genero")
sqlite3.OperationalError: no such table: Genero
2025-06-15 19:50:47,988 - INFO - Programa interrumpido por el usuario
2025-06-15 19:51:46,265 - INFO - Programa interrumpido por el usuario
2025-06-15 19:54:47,759 - ERROR - Error en la inicialización del sistema: near ".": syntax error
Traceback (most recent call last):
  File "c:\Users\Ale\Desktop\Infórmatica\Repos\cine-CG\main.py", line 57, in main
    app.ejecutar()
  File "c:\Users\Ale\Desktop\Infórmatica\Repos\cine-CG\interfaz_usuario.py", line 540, in ejecutar
    self.gestionar_peliculas()
  File "c:\Users\Ale\Desktop\Infórmatica\Repos\cine-CG\interfaz_usuario.py", line 67, in gestionar_peliculas
    self.ver_peliculas()
  File "c:\Users\Ale\Desktop\Infórmatica\Repos\cine-CG\interfaz_usuario.py", line 111, in ver_peliculas
    peliculas = self.cinema_services.obtener_peliculas()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Ale\Desktop\Infórmatica\Repos\cine-CG\servicios_del_cine.py", line 263, in obtener_peliculas
    cursor.execute(query)
sqlite3.OperationalError: near ".": syntax error
2025-06-15 19:57:00,162 - INFO - Programa interrumpido por el usuario
2025-06-15 20:01:11,224 - INFO - Programa interrumpido por el usuario
2025-06-15 20:04:32,355 - ERROR - Error en la inicialización del sistema: ver_horarios() missing 1 required positional argument: 'self'
Traceback (most recent call last):
  File "c:\Users\Ale\Desktop\Infórmatica\Repos\cine-CG\main.py", line 57, in main
    app.ejecutar()
  File "c:\Users\Ale\Desktop\Infórmatica\Repos\cine-CG\interfaz_usuario.py", line 547, in ejecutar
    self.gestionar_horarios()
  File "c:\Users\Ale\Desktop\Infórmatica\Repos\cine-CG\interfaz_usuario.py", line 232, in gestionar_horarios
    self.agregar_horario()
  File "c:\Users\Ale\Desktop\Infórmatica\Repos\cine-CG\interfaz_usuario.py", line 247, in agregar_horario
    ver_horarios()
TypeError: ver_horarios() missing 1 required positional argument: 'self'
2025-06-15 20:08:05,392 - INFO - Programa interrumpido por el usuario
2025-06-15 20:10:43,332 - INFO - Programa interrumpido por el usuario
2025-06-15 20:12:32,931 - INFO - Programa interrumpido por el usuario
2025-06-15 20:12:59,531 - INFO - Programa interrumpido por el usuario
2025-06-15 20:24:15,807 - INFO - Programa interrumpido por el usuario
2025-06-15 20:28:19,394 - INFO - Programa interrumpido por el usuario
2025-06-20 19:00:57,074 - ERROR - Error en la inicialización del sistema: 'UserInterface' object has no attribute 'ejecutar'
Traceback (most recent call last):
  File "c:\Users\Dreamfyre\Desktop\RepositorioGIT\cine-CG\main.py", line 57, in main
    app.ejecutar()
    ^^^^^^^^^^^^
AttributeError: 'UserInterface' object has no attribute 'ejecutar'
2025-06-20 19:01:34,938 - ERROR - Error en la inicialización del sistema: 'UserInterface' object has no attribute 'ejecutar'
Traceback (most recent call last):
  File "c:\Users\Dreamfyre\Desktop\RepositorioGIT\cine-CG\main.py", line 57, in main
    app.ejecutar()
    ^^^^^^^^^^^^
AttributeError: 'UserInterface' object has no attribute 'ejecutar'
2025-06-20 19:03:33,113 - ERROR - Error en la inicialización del sistema: 'UserInterface' object has no attribute 'ejecutar'
Traceback (most recent call last):
  File "c:\Users\Dreamfyre\Desktop\RepositorioGIT\cine-CG\main.py", line 57, in main
    app.ejecutar()
    ^^^^^^^^^^^^
AttributeError: 'UserInterface' object has no attribute 'ejecutar'
2025-06-20 19:03:54,929 - ERROR - Error en la inicialización del sistema: 'UserInterface' object has no attribute 'ejecutar'
Traceback (most recent call last):
  File "c:\Users\Dreamfyre\Desktop\RepositorioGIT\cine-CG\main.py", line 57, in main
    app.ejecutar()
    ^^^^^^^^^^^^
AttributeError: 'UserInterface' object has no attribute 'ejecutar'
2025-06-20 19:08:53,626 - ERROR - Error en la inicialización del sistema: 'UserInterface' object has no attribute 'ejecutar'
Traceback (most recent call last):
  File "c:\Users\Dreamfyre\Desktop\RepositorioGIT\cine-CG\main.py", line 57, in main
    app.ejecutar()
    ^^^^^^^^^^^^
AttributeError: 'UserInterface' object has no attribute 'ejecutar'
2025-06-20 19:14:29,635 - ERROR - Error en la inicialización del sistema: 'UserInterface' object has no attribute 'ejecutar'
Traceback (most recent call last):
  File "c:\Users\Dreamfyre\Desktop\RepositorioGIT\cine-CG\main.py", line 57, in main
    app.ejecutar()
    ^^^^^^^^^^^^
AttributeError: 'UserInterface' object has no attribute 'ejecutar'
2025-06-20 19:23:30,678 - INFO - Programa interrumpido por el usuario
2025-06-20 19:28:42,664 - INFO - Programa interrumpido por el usuario
